apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-valeria
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 19.x # Usamos una versión más reciente del Chart
    chart: redis
    helm:
      values: |
        auth:
          enabled: false
        architecture: standalone
        image:
          tag: latest # Esto asegura que encuentre una imagen válida
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default