apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-valeria
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 15.x.x
    chart: nginx
    helm:
      values: |
        image:
          registry: docker.io
          repository: bitnami/nginx
          tag: 1.27.2
        staticSiteConfig:
          enabled: true
          content: "<h1>GitOps con Bitnami!</h1>"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
