apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-valeria
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 15.x.x
    chart: nginx
    helm:
      values: |
        image:
          registry: docker.io
          repository: bitnamilegacy/nginx
          tag: latest
          pullPolicy: Always
        staticSiteConfig:
          enabled: true
          content: "<h1>GitOps com Bitnami Legacy!</h1>"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default